---
- name: check maldetect already installed | Debian | Maldet
  stat:
    path: "/usr/local/maldetect"
  register: maldetect

- name: "download | Debian  | Maldet"
  get_url:
    url: "{{ maldetect_url }}"
    dest: "{{maldetect_tar_dest_dir }}/maldetect-{{ maldetect_version }}.tar.gz"
  when: maldetect.stat.exists == False

- name: "extract | Debian  | Maldet"
  unarchive:
    src: "{{maldetect_tar_dest_dir }}/maldetect-{{ maldetect_version }}.tar.gz"
    dest: "{{ maldetect_dest_dir }}/"
    copy: "no"
    owner: 'root'
    group: 'root'
    mode: '750'
  when: maldetect.stat.exists == False
  register: extract_maldetect

- name: check maldetect version | Debian  | Maldet
  shell: "find {{ maldetect_dest_dir }} -name maldetect*"
  register: maldet_version
  changed_when: false

- name: "install.sh | Debian  | Maldet"
  shell: "cd {{ maldet_version.stdout }} && ./install.sh"
  when: extract_maldetect.changed

