---
- name: Clamav | install packages | Debian  | Clamav
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'clamav'
    - 'clamav-freshclam'
    - 'clamav-daemon'

- name: Enable {{item}} service | Debian   | Clamav
  shell:  "systemctl enable {{item}}.service"
  changed_when: false
  with_items:
    - 'clamav-daemon'
    - 'clamav-freshclam'

- name: Clamav | start service  | Debian | Clamav
  service:
    name: "{{ item }}"
    state:  'started'
  changed_when: false
  with_items:
    - 'clamav-daemon'
    - 'clamav-freshclam'

- name: Clamav | update freshclam | Debian  | Clamav
  shell: 'freshclam'
  changed_when: false